---
# handlers file for ansible-role-librenms
- name: restart webserver
  service:
    name: "{{ librenms_webserver }}"
    state: "restarted"

- name: restart rrdcached
  service:
    name: "rrdcached"
    state: "restarted"
